ASoC: codecs: fix snprintf size arguments
../techpack/audio/asoc/codecs/wsa881x.c:392:9: error: 'snprintf' size argument is too large; destination buffer has size 20, but size argument is 25 [-Werror,-Wfortify-source]
                len = snprintf(tmp_buf, 25, "0x%.3x: 0x%.2x\n", i,
                      ^
1 error generated.

The warnings are correct. Fix the size arguments by only allowing the
amount of bytes that the size of the char arrays are.

Signed-off-by: shagbag913 <sh4gbag913@gmail.com>
Signed-off-by: Khusika Dhamar Gusti <khusikadhamar@gmail.com>
Change-Id: I31366b5cd2f13f6d168111a4b0a2f013bd6b92f7
(cherry picked from commit ebabc0a7aa3975fb01a4c438d3c0b058f97a72d1)