prima: Remove redefinition of pEncryptMsgRSPCb
Clang spams the build with the following warnings (trimmed):

  In file included from /mnt/ssd/kernels/mido/CORE/MAC/src/pe/lim/limStaHashApi.c:39:
  In file included from /mnt/ssd/kernels/mido/CORE/MAC/src/pe/lim/limStaHashApi.h:45:
  In file included from /mnt/ssd/kernels/mido/CORE/MAC/inc/aniGlobal.h:73:
  In file included from /mnt/ssd/kernels/mido/CORE/SME/inc/csrInternal.h:55:
  In file included from /mnt/ssd/kernels/mido/CORE/SME/inc/csrNeighborRoam.h:42:
  /mnt/ssd/kernels/mido/CORE/SME/inc/sme_Api.h:3859:15: warning: redefinition of typedef 'pEncryptMsgRSPCb' is a C11 feature [-Wtypedef-redefinition]
  typedef void(*pEncryptMsgRSPCb)(void *pUserData, void *infoParam);
                ^
  /mnt/ssd/kernels/mido/CORE/SME/inc/smeInternal.h:138:15: note: previous definition is here
  typedef void(*pEncryptMsgRSPCb)(void *pUserData, void *infoParam);
                ^

Since sme_Api.h includes smeInternal.h, we can safely remove the
definition from sme_Api.h without breaking the entire build.

Signed-off-by: Albert I <kras@raphielgang.org>
(cherry picked from commit a0eaae88e9c18f7a2cd62717baa68bed6066145d)
Signed-off-by: GeoPD <geoemmanuelpd2001@gmail.com>